### ISSUE TITLE
mmap to reduce memory usage of spacy.en.English instances

### ISSUE THREAD

**Issue by rw** [honnibal/spaCy#100]
I notice that a fully-initialized spacy.en.English instance can take over 2GB of RAM.

Are there plans to optionally use memory mapping for NLP data to reduce memory usage? This would be useful when developing locally.

A format like FlatBuffers (https://google.github.io/flatbuffers/), designed for mmaping, could be useful for this.

**Comment by honnibal** [comment]
Most of the memory use is in the parser model, which is so large because of data sparsity.

I've done about 60% of the work to move to a neural network model, which would make the model much much smaller, and should also improve accuracy.

So: I'd rather not take on the extra complexity from mmap. Even though I do develop on a 4gb Macbook Air, so I feel the pain too :).

**Comment by rw** [comment]
@honnibal Sounds like a plan :-)
