### ISSUE TITLE
pos tagger not giving determiner tag

### ISSUE THREAD

**Issue by aliabbasjp** [honnibal/spaCy#102]
doc = nlp(u'That man stared at the old oak tree.')

>>> map(lambda a: a.pos_, doc)
Out[4]: [u'ADJ', u'NOUN', u'VERB', u'ADP', u'ADJ', u'ADJ', u'NOUN', u'NOUN', u'PUNCT']

why is it tagging ADJ instead of DET???

Same in the online demo, But I need the det tag , can we extend some class and accomplish it?

**Comment by honnibal** [comment]
Thanks --- this is a mistake introduced in a recent version. I rewrote the tag mapping while working on making spaCy multi-lingual, and this error has been introduced.

As a temporary work-around for you, until the next version is released, use the `.tag` attribute, and add a mapping table to your code with the correct mapping.

**Comment by aliabbasjp** [comment]
what is the difference between the .tag_ and .pos_ ?

**Comment by aliabbasjp** [comment]
can i just go to lang_data/en/tag_map.json in my local installation and change that?

**Comment by honnibal** [comment]
The .pos attribute gives a basic part-of-speech tag, one of the 17 tags
from the "universal" (i.e. cross-lingual) annotation scheme. This gives
tags like NOUN, VERB, DET, etc.

The .tag attribute gives a data-specific tag like VBZ, NNS, DT, etc. These
tags include morphological information, as well as the part-of-speech. This
type of tag is used in computational linguistics because it's an important
feature for statistical modelling.

Most part-of-speech taggers for English return values like the .tag
attribute, from the 45-tag Penn Treebank tag set. However, most users will
find the .pos tag more useful for many purposes, as it means you don't have
to learn about the data-specific (and somewhat arbitrary) annotation
scheme.

**Comment by honnibal** [comment]
The relevant file will be at spacy/en/data/vocab/tag_map.json . Modifying
that should work.
