### ISSUE TITLE
0.93 bug in parser (or unintuitive interface)

### ISSUE THREAD

**Issue by evanmiltenburg** [honnibal/spaCy#116]
Minimal example:

    # First, let's import the two modules we need.
    import spacy.en

    # Create an English nlp-object from the spacy.en module.
    nlp = spacy.en.English(parser=True, tagger=True, entity=True)

    # Define some text to play with (copy-pasted from WIRED.com)
    text = """But right now, I could not see the ground, even though my window was wide open. 
    All I could see was the sky, and all I can remember is the high-pitched whine of that alarm.
    And then the strangest thing happened: nothing. 
    We didn’t go into a spin. Instead, the plane just kind of floated, nose up, in midair. """

    # And process the text:
    doc = nlp(text)

This produces the following error:
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-3-e7274a269ad4> in <module>()
          6 
          7 # And process the text:
    ----> 8 doc = nlp(text)

    //anaconda/envs/py3k/lib/python3.3/site-packages/spacy/language.py in __call__(self, text, tag, parse, entity)
        227         tokens = self.tokenizer(text)
        228         if self.tagger and tag:
    --> 229             self.tagger(tokens)
        230         if self.matcher and entity:
        231             self.matcher(tokens)

    TypeError: 'bool' object is not callable

This is probably the same bool as the one I used when calling the module. But in the tutorial it said:
    "To disable (and avoid loading) parts of the processing pipeline:"
    >>> nlp = English(parser=False, tagger=False, entity=False)

So I assumed that the converse was also true. Apparently this is not the case.

**Comment by honnibal** [comment]
Thanks.

This was an interface and docs issue. The behaviour is:

`parser=None` (default): Load the default parser, via `Language.default_parser`
`parser=False`: Don't load a parser.
`parser=user_class`: Use the user-supplied parser callable.

I've changed it so that `parser=True` now loads the default. I'll keep `parser=None` also loading the default for backwards compatibility for the moment, but probably this should be equivalent to `parser=False`, not `parser=True`.
