### ISSUE TITLE
Use universal dependencies for cross-lingual consistency

### ISSUE THREAD

**Issue by jimmycallin** [honnibal/spaCy#128]
[Universal dependencies](https://universaldependencies.github.io/docs/introduction.html) (UD) is a new dependency framework with extensive work across 30+ languages. One of the main benefits is that using UD for parsing, the annotation scheme becomes much more consistent across the supported languages. I would suggest that you look into supporting this work.

**Comment by honnibal** [comment]
We're working towards this.

The priority at the moment is to support the morphological analysis scheme. You can see discussion of it here: https://github.com/UniversalDependencies/docs/issues/212

Our current roadmap is to get other languages working for tokenization, tagging, morphological analysis, lemmatization and word vectors. We'll then work on named entity recognition and parsing for for these languages. Finally, we'll offer UD syntactic models for English.

Currently UD seems like it will result in lower accuracy for English than the OntoNotes-based, ClearNLP converted model we're offering. The ClearNLP converter produces very good output, because the conversion makes use of the trace and function annotations in the treebank, which the Stanford converter ignores.

I suspect that good parser accuracy with UD may depend on learning an intermediate representation, and applying post-process transformations. So I'm reluctant to adopt the scheme until I have time to experiment with this.

**Comment by seoninja13** [comment]
Honnibal, 
since it has been more than a year from the previous request/disscussion for UD integration, how are things looking now..??

Thanks,
