### ISSUE TITLE
Errors running vector tests when building from source

### ISSUE THREAD

**Issue by chrisdubois** [honnibal/spaCy#146]
What extra commands are required in order to have `tests/vectors/*` pass? It might be nice to have the travis build include these commands and run the full test suite; are there reasons to skip `vectors`, `models`, etc?

In other words, it's not clear (to me) how to download all the required data when building from source either by following `.travis.yml` or using the fabfile. I tried `python -m spacy.en.download all`, and I tried to copy all the data into the right places, but I still get an error about vectors size being 0 after calling `nlp('blah').vector`, i.e., it didn't properly load the vectors binary. 

I hope I haven't missed something obvious. Thanks in advance for any hints!

**Comment by honnibal** [comment]
A couple of different issues here, about stuff I'm not at all satisfied
with currently.

1) We really need to be testing a much more complicated matrix, with all
the various ways data can be loaded in, the code can be installed, and the
way Python can be configured. We're working on this. We'll likely move off
Travis.

2) a specific issue is that we dont want the Travis tests to require the
data, as it's more memory than is comfortable for the free tier.

3) the download.py script is pretty crude atm. We're steadily fixing this,
and making it more like a package manager.

So. Apologies that the experience is a bit crap currently.

It sounds likely you're having one of three issues:

A) your PYTHONPATH isnt set. If you do "python -c; import spacy.en;
print(spacy.en.__file__)" does the result look correct? If not, try

    export PYTHONPATH='pwd'
(But use back ticks instead of apostrophes -- im on my phone)

B) is the correct py.test being run? Try "which py.test"

C) try adding the --force command to the download command. We recently
modified the script, maybe this is necessary now and we have to update the
docs.

**Comment by chrisdubois** [comment]
Thanks for the quick reply!

1. I very much understand about wanting a bigger test matrix. Python 2.7/3.4 and linux/OS X seems like a great start.
2. Ah, that makes sense. To run/test things locally, are there extra steps (that download data to the right place) that aren't currently in `fabfile.py`? (I'm thinking that having a single script that travis runs would be nice, albeit without testing --vectors. I would guess it'd be some reincatation of fabfile.py:24-57.)
3. Yes, but it's quite handy already!

I'm confident that my path is set to `pwd`, but I hadn't tried that force flag. After doing that, it seems to have placed data in `spacy/en/data/data` rather than `spacy/en/data` due to [this line](https://github.com/honnibal/spaCy/blob/master/spacy/en/download.py#L18). Is this expected? Moving everything to `spacy/en/data` seems to have fixed things. 

Thanks!

**Comment by honnibal** [comment]
Yep, there's a bug here. I suspect @henningpeters developed this under Linux, and got tricked by the different copy semantics in BSD?

Anyway. We'll fix this, thanks!

**Comment by chrisdubois** [comment]
I think it's simply that the `tgz` contains a data folder, and it gets downloaded to `spacy/en/data`. Setting `DEST_DIR =path.dirname(path.abspath(__file__)` should work fine, given the current state of `en_data_all-0.9.5.tgz`.

FWIW I'm Ubuntu 14.04.

**Comment by henningpeters** [comment]
Thanks, you are close, but the problem was removing ```path.dirname(DEST_DIR)``` from [this line](https://github.com/honnibal/spaCy/blob/e886e6a4064249f953f90aee6b7656bdc91715cd/spacy/en/download.py#L48). Fixed it, but its a kludge (real solution is already on the way), pull request is [here](https://github.com/honnibal/spaCy/pull/145)

**Comment by chrisdubois** [comment]
I confirmed the PR mentioned above works. Thanks!

Before we close this issue, shouldn't `python -m spacy.en.download all` be called by a setup script somewhere? Right now it's only mentioned in documentation. I'm not sure whether you'd prefer boostrap_python_env.sh, fabfile.py, setup.py, or just .travis.yml, but I think it should be somewhere for those who are trying to run tests on a new machine. If you have a preference on location, I'd be happy to add it.

**Comment by henningpeters** [comment]
We are currently reworking this part of the codebase into a minimal data package manager, hence would like to avoid any confusion regarding the call pattern as we might have to introduce yet another entry point soon. An early prototype for the new project is here: https://github.com/henningpeters/shuttle, if you are interested in contributing I can write up some stuff that I thought about so far...

**Comment by chrisdubois** [comment]
I see. Interesting! I look forward to seeing how that goes.

If it really is a package manager that you seek -- even if data is involved -- have you considered just using conda?

**Comment by chrisdubois** [comment]
Also: Given things are heading in that direction, it probably makes sense to close this issue.

**Comment by henningpeters** [comment]
I think conda is a great package manager for binaries (I maintain the spacy conda builds), but apart from technical reasons we were concerned making spacy depend on conda or any other OS level package manager. The main thing that is different on a technical level (minus optimizations for large data sets) is that shuttle is embeddable: ```import shuttle``` somewhere and spaCy (or any other project that needs to maintain data) has first-class control over the installed data, it neither is a new package manager the user has to buy into nor requires the user to change his development environment. Having said that, I hope we are not reinventing the wheel here.

**Comment by chrisdubois** [comment]
Sounds good.
