### ISSUE TITLE
Is the word vectors GloVe or Goldberg ones?

### ISSUE THREAD

**Issue by jli05** [honnibal/spaCy#192]
Could we confirm and update in the online docs? Thanks,

**Comment by honnibal** [comment]
The word vectors are from Levy and Goldberg. That's what the docs say, right?

**Comment by jli05** [comment]
Thanks for confirmation. Is there any plan to migrate to GloVe by default in any foreseeable roadmap? (Probably that'd involve work to optimise the loading time)

**Comment by honnibal** [comment]
I do want to switch to the GloVe vectors, but I want to have a bit of an
evaluation set up.

There's been some delay on this. I've been working on switching spaCy to
use a feed-forward neural network, instead of the averaged perceptron. The
word vectors would be fine-tuned for the parser and tagger.

The question is whether the parser/tagger vectors will be well suited for
general similarity use, or whether there will need to be separate vectors
for that. I'd like to put a heavy regulariization penalty on the vector
fine-tuning, to try to find a good parser model that's close to the
original GloVe vectors.

In hindsight I probably should've switched to the GloVe vectors already. I
thought this work would be completed a little sooner, and I didn't want to
change vectors twice.

To load vectors faster, the answer is simply to load a smaller vocabulary.
If the vocabulary is frequency-sorted, there's very little utility in
loading such an enormous vocabulary, like the GloVe vectors provide. It's
great that they provided the full vectors --- because if you need all of
them, e.g. for spelling correction or some niche long-tail use-case, it's
important that the full resource is distributed.

But almost nobody needs to load all that data. The vast, vast majority of
applications will be fine loading, say, 200,000 vectors. That means the
loading will be pretty fast.
