### ISSUE TITLE
Nested noun chunks

### ISSUE THREAD

**Issue by matichorvat** [honnibal/spaCy#203]
In Spacy documentation, noun chunks are defined as: "A base noun phrase, or "NP chunk", is a noun phrase that does not permit other NPs to be nested within it".

Does this not mean that noun chunks should not be nested?

In this example, this is not the case:
```
from spacy.en import English
nlp = English()
sent = u'''Peter has chronic command and control issues.'''.strip()
tokens = nlp(sent)
for chunk in tokens.noun_chunks:
    print chunk.orth_
```
```
Peter
control
chronic command and control issues
```

**Comment by honnibal** [comment]
Hmm.

Good point. It seems I changed the definition of this and didn't change the docs. I'm now not sure why I set the definition to include the `conj` relation:

https://github.com/honnibal/spaCy/blob/master/spacy/tokens/doc.pyx#L244

More broadly, I'm now not so sure I'm happy with the design decision to put the iterator as a property of the `Doc` object. It seems like it would be better to have a library of these iterators, which should be functions. So you would have `noun_chunks(doc)` instead of `doc.noun_chunks`

**Comment by matichorvat** [comment]
Thanks for your reply. So is the desired functionality that the noun chunks can be nested?

**Comment by honnibal** [comment]
No --- the output is wrong. I'll fix this.

**Comment by matichorvat** [comment]
Thanks!

**Comment by honnibal** [comment]
Now returns
```
Peter
chronic command and control issues
```
