### ISSUE TITLE
Reconciling tokens with NE spans

### ISSUE THREAD

**Issue by rlvoyer** [honnibal/spaCy#213]
I'm curious if there's a built-in mechanism for traversing a view of a sentence or a document with knowledge of both named entities as well as tokens. For example, say I'd like to iterate over a sentence yielding the lemma of each non-stopword token, unless it's part of a named entity span, in which case I'd like to yield the surface form of the NE span, and then continuing on to the token immediately following the NE span. Is there a built-in way to handle this? I can't find any relevant examples in the documentation. Thanks for your help.

**Comment by honnibal** [comment]
Sure. Use the tok.ent_type and tok.ent_iob attributes

tok.ent_iob is a bit confusing:

0 is no tag
1 is I
2 is O
3 is B

Probably the easiest thing to do though is to use .merge(), a method
available on the span object, or on the doc object. The following should
work:

for ent in doc.ents:
    ent.merge(ent.text, ent.root.tag_, ent.label)

This will retokenize the document, so that entities are excluded. Your
function would then be:

for token in doc:
    if not token.is_stop:
        yield token.lemma_

Note that you can rebind is_stop across the vocabulary:

for lexeme in nlp.vocab:
    lexeme.is_stop = my_is_stop(lexeme.orth_)

This way my_is_stop is only computed once per type, not once per token. You
can also set the function in the Vocab object, so that unseen lexemes are
given a value using this function.

Please see the docs for all this code. I haven't tested it, so I may have
some things wrong :).

Also the functionality of merging spans while iterating over them is new
and a bit ambitious. There may be bugs. If so, please report, and the
workaround is to first collect tuples with the arguments to Doc.merge,
which refers to character offsets, and then merge the spans from these
tuples.

**Comment by rlvoyer** [comment]
Oh, ok. What's the difference between 0 and 2? I'm accustomed to seeing the BIO tagging format, where "O" (ie 2, in the Spacy ent_iob enum) is applied to all tokens not within an entity span. And actually, I'm looking at a Spacy Doc and I don't see any tokens with an ent_iob value of 0:

```python
{x.ent_iob for x in doc}
{1, 2, 3}
```

Merge seems to work as advertised. This is great. (FWIW, I think you had the args to `merge` transposed above.) The following worked for me:

```python
doc = nlp(u"Can you believe Donald Trump is running for president in 2016?")

[t.lemma_ for t in doc]
[u'can',
 u'you',
 u'believe',
 u'donald',
 u'trump',
 u'be',
 u'run',
 u'for',
 u'president',
 u'in',
 u'2016',
 u'?']

[t.lemma_ for t in doc]
[u'can',
 u'you',
 u'believe',
 u'Donald Trump',
 u'be',
 u'run',
 u'for',
 u'president',
 u'in',
 u'2016',
 u'?']
```

**Comment by Imane0** [comment]
With spacy 2.0.4, I get a different output:
```
In [110]: doc = nlp(u"Can you believe Donald Trump is running for president in 2016?")
     ...: 
     ...: [t.lemma_ for t in doc]
     ...: 
Out[110]: 
[u'can',
 u'-PRON-',
 u'believe',
 u'donald',
 u'trump',
 u'be',
 u'run',
 u'for',
 u'president',
 u'in',
 u'2016',
 u'?']
In [111]: for ent in doc.ents:
     ...:     if ent.label_ == "PERSON":
     ...:         ent.merge(ent.root.tag_, ent.text, ent.label_)
     ...: 
     ...: [t.lemma_ for t in doc]
     ...: 
/home/imane/anaconda2/bin/ipython:11: DeprecationWarning: Positional arguments to Doc.merge are deprecated. Instead, use the keyword arguments, for example tag=, lemma= or ent_type=.
  load_entry_point('ipython==5.4.1', 'console_scripts', 'ipython')()
Out[111]: 
[u'can',
 u'-PRON-',
 u'believe',
 u'donald',
 u'be',
 u'run',
 u'for',
 u'president',
 u'in',
 u'2016',
 u'?']

```
