### ISSUE TITLE
Merge hangs

### ISSUE THREAD

**Issue by sdenning** [honnibal/spaCy#214]
Great job on SpaCy, it is really impressive!

I'm pos tagging news articles and merging the tags for the named entities. Many thousands of the articles are fine. Merge hangs up on the text here though.

```python
from __future__ import unicode_literals

import spacy.en
from spacy.en import English

nlp = English()
doc = nlp('text', tag=True, parse=True)

text = '"But there is no telling what the hurricane damage will be," Anderson said, in reference to Hurricane Fran which swept through North and South Carolina last week. Some industry sources said the hurricane may have brought beneficial rains while others predicted losses and damage to open bolls. "Fran changes the picture considerably but it is too soon (to determine losses)," said Jarral Neeper, an analyst with Calcot Ltd. He pegged the estimate at 18.717 million bales. Smith Barney analyst David Brandon compared the effect of Hurricane Fran to that of Hurricane Hugo in 1989, which he said buoyed yields in North and South Carolina.'

doc = nlp(text, tag=True)

for ent in doc.ents:
    if len(ent.orth_.split()) > 1:
      start = text.index(ent.orth_)
      end = start+len(ent.orth_)
      print ent.orth_ + ' start: ' + str(start) + ' ' + 'end: ' + str(end) + ' ' + 'entity: ' + ent.label_
      doc.merge(start, end, '', '', ent.label_)
      for token in doc:    
          print token.orth_
```

Here's the output I get:
```
Hurricane Fran start: 92 end: 106 entity: EVENT
South Carolina start: 137 end: 151 entity: GPE
last week start: 152 end: 161 entity: DATE
Jarral Neeper start: 381 end: 394 entity: PERSON
Calcot Ltd. start: 412 end: 423 entity: ORG
18.717 million bales start: 450 end: 470 entity: QUANTITY
Smith Barney start: 472 end: 484 entity: ORG
David Brandon start: 493 end: 506 entity: PERSON
Hurricane Fran start: 92 end: 106 entity: EVENT
Hurricane Hugo start: 556 end: 570 entity: EVENT
North and South Carolina start: 127 end: 151 entity: GPE
```

**Comment by sdenning** [comment]
I think I've found the problem here. Spacy's NER adds the 1st 'North' to the entities list, then adds the 1st 'South Carolina'. Later Spacy adds the entire 2nd 'North and South Carolina' to the entities list. When I iterate through the list and try to merge the 1st 'North and South Carolina' merge never returns, most likely because 'South Carolina' was already merged.

Is there something that could be done so that Spacy's NER is consistent with both instances of 'North and South Carolina' i.e. multiple instances of the same substring? Also, could you add a check and error code to merge so that if tokens have already been merged an error code is returned rather than the function hang?

Thanks.

**Comment by honnibal** [comment]
Hey,

Thanks a lot for this. We've been a bit unresponsive on the tracker lately, compared to normal. I've been busy porting the machine learning model to a neural network, which will decrease load times and help us use the latest research. Henning has implemented an awesome testing framework, and redesigned the build process.

We had problems with these sub-matches in a previous ticket, and it looks like my patch has caused this problem. We need to do something more clever here.

**Comment by honnibal** [comment]
Working on this.

Have the local issue sorted no problem. But the deeper thing is we shouldn't be entering an infinite loop, under any circumstances. So I located that, which is due to a cycle in the parse tree, created during a previous merge. Tracking that down now.

**Comment by sdenning** [comment]
Great, thanks for working on this.

On Jan 15, 2016, at 12:36 PM, Matthew Honnibal <notifications@github.com<mailto:notifications@github.com>> wrote:


Working on this.

Have the local issue sorted no problem. But the deeper thing is we shouldn't be entering an infinite loop, under any circumstances. So I located that, which is due to a cycle in the parse tree, created during a previous merge. Tracking that down now.

**Comment by honnibal** [comment]
Okay, this was a really nice case. Thanks for the report, it fixed a subtle but significant bug.

The underlying issue was with the way `Span` objects were determining their "root" word --- the word by which they're attached to the rest of the parse tree. This was being done by looking for the first word in the `Span` that had its head outside the `Span`.

This was incorrect for cases like `North and South Carolina`, where the head of `South` is `North`, and the head of `North` is `Carolina`. Regarding `South` as the root of the `Span` implies a parse tree with a cycle. This cycle eventually caused the infinite loop, when combined with another defect in the `Span.root` method: it assumed but didn't check that the parse was in a consistent state.

I've now rewritten `Span.root` so that root is determined by counting the path-length up the tree, and doing an arg min over the measure. This is not `O(n)`, and a `Span` might be a sentence, which is quite long. To make sure we don't have a problem for that case, the code first loops through the `Span`, and if a word is the root of a sentence, it simply returns it.
