### ISSUE TITLE
How to use custom stop words?

### ISSUE THREAD

**Issue by poliquin** [honnibal/spaCy#226]
I find the following behavior confusing:

```python
>>> from spacy import en
>>> en.STOPWORDS.add('hello')
>>> nlp = en.English()
>>> nlp.is_stop('hello')
1
>>> sent = nlp('He said hello')
>>> sent[-1].is_stop
False
```

What is the correct way to use custom stop words with spaCy?

**Comment by honnibal** [comment]
The catch here is that properties like `is_stop` etc are computed once per lexeme, and the loading of the data in `nlp = en.English()` loads pre-computed results. This allows us to set lots of potentially expensive lexeme properties, with almost no performance penalty, because caching is so effective over NLP vocabularies. On the other hand --- cached data can lead to some unexpected results.

You can write to any of these properties via the `Lexeme` object. Example:

```python
for word in en.STOPWORDS:
    lexeme = nlp.vocab[word]
    lexeme.is_stop = True
```

The vocab is also iterable:

```python
for lexeme in nlp.vocab:
    lexeme.is_stop = lexeme.orth_ in my_stop_words
```

Stop words are a bounded set, but for some other types of property changes, you'll want to register a new function in `nlp.vocab.get_lex_attrs`. For instance:

```python
from __future import print_function, unicode_literals

def normalize(word):
    if word.isdigit() and len(word) == 4:
        return u'!YEAR'
    elif word[0].isdigit():
        return u'!DIGITS'
    else:
        return word.lower()

import spacy.en
import spacy.attrs

nlp = spacy.en.English()
for lexeme in nlp.vocab:
    lexeme.norm_ = normalize(lexeme.orth_)
nlp.vocab.get_lex_attr[spacy.attrs.NORM] = normalize

doc = nlp(u'This is an acid-test of string norm in 2016')

assert doc[-1].nrom_ == u'!YEAR'
```

Obviously this isn't a great API. We need to add some methods to `Vocab` to register these attribute calculation functions, which will update the calculated values. Thanks for reminding me.

**Comment by poliquin** [comment]
Thanks for the fast, excellent reply and your hard work on this library!
