### ISSUE TITLE
Download data

### ISSUE THREAD

**Issue by rjsbhatia** [honnibal/spaCy#246]
Hi, 

I am having trouble downloading data using the command
python -m spacy.en.download all 
or
python -m spacy.en.download 

It gives a value error, 
ValueError: numpy.dtype has the wrong size, try recompiling

I noticed when searching on google, other people had this issue with numpy while installing pandas. My numpy version seems to be the latest. Which version of numpy does spacy use? 
Or is there some other way of downloading the data files?

Thanks,

**Comment by honnibal** [comment]
Hey,

The error means that the numpy that spaCy is trying to load at run-time is different from the one used at compile time. This might be because some other library has conflicted requirements, or some PYTHONPATH/virtualenv/python version/etc trickery that means you're executing in a different way from how you installed.

I often just delete the virtualenv and start a new one when this happens, because it's often faster than figuring out what's wrong. Another way is to uninstall numpy and reinstall it.

**Comment by rjsbhatia** [comment]
Thanks for the quick reply. I am wondering if there is a way to manually download the data needed for spacy to work? It installed properly, its missing the data.

**Comment by honnibal** [comment]
You can download the data manually, but if you do `import spacy.en.download` I think you'll find it's not installed correctly.

**Comment by rjsbhatia** [comment]
Thanks again, i will try to do a new install.
