### ISSUE TITLE
Make spacy.en.English() 10× faster

### ISSUE THREAD

**Issue by suchow** [honnibal/spaCy#40]
I'd like to use spaCy as part of a command line utility that will run an analysis over a single document. The parsing and tagging is blazingly fast, which is great. But calling `spacy.en.English()` takes over a second on my system, which is 10× too long for my purporses. Is there any hope for me?

**Comment by syllog1sm** [comment]
You'll need to run spacy as some sort of long-running server process, which your client communicates with.

I've tried to keep start up times low by using efficient binary file formats, but less than a second is unrealistic --- spacy needs to load its model files.

I assume you don't want to program in Python? If you do, you should just load spacy in your top-level module, and pass it around, as you iterate over your document collection.

**Comment by suchow** [comment]
Python is perfectly fine, preferred actually. The trouble is that I only really have one document. I'll be running my analysis on the file as it changes over time (at most once every few seconds), but I want the analysis to complete quickly, ideally in under 300 ms. It sounds like I'll need to follow your suggestion of using a long-running background process that the command line utility communicates with. Do you know of an existing Python utility that uses that architecture, for reference?

**Comment by honnibal** [comment]
Why can't you just watch the file for changes from a Python process?

I mean...ultimately your problem is to feed text into Python at regular
intervals. I'm sure you can find some way to do this.

If you like writing in Python, I would suggest that having spaCy output to
the command line will be much worse than using its API. Presumably you also
need to use the annotations for something, right? Writing to file, reading
in, and then rewriting your own API should be unnecessary.

**Comment by suchow** [comment]
Thanks, this was helpful!
