### ISSUE TITLE
Dependency Relation Types

### ISSUE THREAD

**Issue by seamatth** [honnibal/spaCy#61]
I've noticed that the dependency relation types that I get from the dependency parser in spaCy are a bit different than the Stanford dependencies.  Is there some kind of mapping between the these dependency types and the Stanford dependencies?

**Comment by honnibal** [comment]
SpaCy currently uses the Yamada and Matsumoto (2003) dependency scheme, one of several different schemes in use by researchers. I opted for this scheme because some research has found it more accurate for down-stream applications than Stanford, and the smaller number of dependency types can make hard-coding logic easier.

You can see more details about the scheme and the tool used to produce it here: http://stp.lingfil.uu.se/~nivre/research/Penn2Malt.html
