### ISSUE TITLE
Mysterious assertion error

### ISSUE THREAD

**Issue by Copper-Head** [honnibal/spaCy#64]
Hi!

Thanks a bunch for the package, it looks cool! We're trying it out at our lab but unfortunately running into an error. Below is the problematic code snippet:

```python
>>> from spacy.en import English
>>> nlp = English()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/quickbeam/.virtualenvs/cuttlefish/lib/python2.7/site-packages/spacy/en/__init__.py", line 72, in __init__
    get_lex_props=get_lex_props)
  File "spacy/vocab.pyx", line 46, in spacy.vocab.Vocab.__init__ (spacy/vocab.cpp:2420)
  File "spacy/vocab.pyx", line 164, in spacy.vocab.Vocab.load_lexemes (spacy/vocab.cpp:4059)
AssertionError
```

Not being too familiar with Cython, I was unable to find the relevant *vocab.pyx* file and see what was being asserted on those lines.
Let me know if there is anything you need from me in terms of info about my system etc.

Best,
Ilia

**Comment by elyase** [comment]
did you do:
```bash
 python -m spacy.en.download
```
?

**Comment by Copper-Head** [comment]
Ah, I should have mentioned this. I did run that command and it completed with no errors. Thanks for checking!

Re Stackoverflow: do you think I should cross-post there too?

**Comment by elyase** [comment]
It still looks like the data is not being found, the data directory should be here:

```bash
python -c "import spacy.en; print spacy.en.__file__"
```
Can you look around?

Re: Stackoverflow: I just mentioned as a general comment, at the moment you will get more visibility here.

**Comment by honnibal** [comment]
Here's the line in question:

https://github.com/honnibal/spaCy/blob/master/spacy/vocab.pyx#L164

This should return a proper error; I'll fix that.

But as for the actual problem: 

The lexemes.bin data file is a list of (orth_id, lexeme_struct) pairs, where the orth_id is actually redundant --- the lexeme struct has a member with this value. I keep it there as an integrity check. It's this integrity check that's just failed.

To explain the code: Line 155 reads an integer from the file handle, and loads it into the variable "orth". We then read the Lexeme struct from the file, and check that the lexeme's ID matches the ID of "orth".

So, either I'm shipping broken data, or the data has in some way become broken on your file system. Could you be out of disk space?

The following (awkward) bash command will print an MD5 checksum of the relevant file:

    $ md5 `python -c "import os.path, spacy.en; print (os.path.join(os.path.dirname(spacy.en.__file__), 'data', 'vocab', 'lexemes.bin'))"`
MD5 (spacy/en/data/vocab/lexemes.bin) = cffe7d058ec136ac98a43faf80ac8848

Could you run that (with your virtualenv loaded, so that spacy imports correctly) and tell me the result?

My result is:

    MD5 (spacy/en/data/vocab/lexemes.bin) = cffe7d058ec136ac98a43faf80ac8848

**Comment by Copper-Head** [comment]
Thanks for the prompt responses!

I'll address both comments, though Yasser's indirectly.

@honnibal, I don't think I'm low on space (only using half of my drive), but somehow when I ran your bash command (*note*: I had to replace `md5` with `md5sum` on my xubuntu box), I got a different output than you:
`ab0cc5bb4e916400e90fdd2522963acc  /home/quickbeam/.virtualenvs/cuttlefish/lib/python2.7/site-packages/spacy/en/data/vocab/lexemes.bin`.

**Comment by elyase** [comment]
I also get `ab0cc5bb4e916400e90fdd2522963acc` on a working installation (OS X).

**Comment by honnibal** [comment]
Ah this was my goof --- on my test machine I get that MD5 too. My local copy has modification that I'd forgotten about.

Hmm.

I can't replicate this problem. I've just quickly done a fresh install, and it works as expected. And apparently your data is correct. For now I'm out of ideas? I'll think about this and get back to you.
