### ISSUE TITLE
Incorrect lemma from lemmatizer

### ISSUE THREAD

**Issue by NSchrading** [honnibal/spaCy#69]
The lemma for the adjective "better" is usually "good", and in fact in the exceptions file for lemmas (adj.exc) you have listed for "better" the lemmas "good" and "well". However, when the word "better" is tagged as an adjective its lemma is still "better". 

```python
from spacy.en import English
nlp = English()
s = "I got better"
toks = nlp(s)
toks[2].pos_
>>> 'ADJ'
toks[2].lemma_
>>> 'better'
```

Checking out the Lemmatizer class it appears to return correct lemmas, although better is still in the set.

```python
lemmatizer = Lemmatizer(path.join(DATA_DIR, 'wordnet'), NOUN, VERB, ADJ)
print(lemmatizer("better", ADJ))
>>> {'well', 'better', 'good'}
```

As an aside, how does spaCy choose which of the returned lemmas from the function lemmatize() to use?

**Comment by honnibal** [comment]
Hey,

Sorry I didn't get to this sooner.

This part of the library is a bit disorganised. Basically there's a separate mechanism to do POS-tag driven morphological disambiguation. In lang_data/en/morphs.json, you can enter word forms under a given POS tag, and then give their lemma and some set morphological features based on the tag.

The entry for better / best was missing from this table. I've since added it.
