### ISSUE TITLE
spacy/attrs.pxd missing

### ISSUE THREAD

**Issue by jnothman** [honnibal/spaCy#7]
Hey- compile (in fact, Cython translation) is failing due to uncommitted file (that should have been in the repo for 9 days). I think since this is now being advertised, you should probably move to off-site CI and tagged releases...

**Comment by jnothman** [comment]
(Oh, and best of luck for the project!)

**Comment by honnibal** [comment]
Hey

Argh, thanks. I'm using Travis, but I'm testing installation via pip. The attrs.pxd file ends up in the sdist, because it's in the package data.

I need to CI both installation from git clone and installation via pip. I'll figure that out.

**Comment by jnothman** [comment]
Yes, always sdist from a fresh clone

**Comment by jnothman** [comment]
You need a CI that tests master, and all pull requests, ideally (although I'm not sure what scale of contribution you expect/intend on this licensing model). It's pretty standard integration on github.

**Comment by honnibal** [comment]
The problem is that the sdist relies on an intermediate state not in the repo --- the Cython-generated .cpp files. I have the CI set up to test the sdist because it's actually not so simple to build the .cpp files in a way that ensures the sdist doesn't depend on some side-effect of the Cythonizing.

Anyway. I'll find a way to fix this and ensure that both the installation from pip and the compilation from master are clean.
