### ISSUE TITLE
0.87 initialization takes much longer

### ISSUE THREAD

**Issue by viksit** [honnibal/spaCy#74]
With 0.87, doing a simple nlp("foo") takes 22.3544478416 seconds, whereas it was on the order of magnitude of 6-10 seconds with previous versions. Is there something to change here?

**Comment by honnibal** [comment]
This is partly due to the change in the model format, which reduced the memory of the model, but takes a little longer to load. It can be reduced a little bit by being more risky in the way the model is loaded, but not by very much.

Hopefully soon I'll have a neural network model working and the model will be much smaller.

**Comment by viksit** [comment]
Thanks for the feedback - when do you think the CNN will be ready? Any contributions on that front you're accepting?

**Comment by dkleissa** [comment]
Agree model load time is actually starting to be problematic for me the more i've played with spaCy (although I do like it a lot otherwise).

I try to consolidate in my application where spaCy is needed, so I only load the model in 1 class, but I'm starting to run into times where I want to do something simple (i.e. tokenization) elsewhere and don't want to eat the time it takes to initialize a new instance, but also don't want to make extra complex code and have to pass the spaCy instance around.

Is there any way to reduce initialization time for a case like this?  I tried:

    nlp = English(load_vectors=False, Parser=True, Tagger=False, Entity=False)

But get an exception: 

    Parser = lambda s, d: parser.Parser(s, d, transition_system)

**Comment by honnibal** [comment]
I get the following:

(.env)Matthews-MacBook-Air:spaCy matt$ time python -c "import spacy.en; nlp
= spacy.en.English();"

real 0m53.477s
user 0m36.446s
sys 0m6.252s
(.env)Matthews-MacBook-Air:spaCy matt$ time python -c "import spacy.en; nlp
= spacy.en.English(Parser=False);"

real 0m10.704s
user 0m7.449s
sys 0m1.371s
(.env)Matthews-MacBook-Air:spaCy matt$ time python -c "import spacy.en; nlp
= spacy.en.English(Parser=False, load_vectors=False);"

real 0m7.643s
user 0m6.048s
sys 0m0.827s

So, almost all the time can be cut by writing Parser=False.

Maybe you should have something like a singleton? Maybe have a module like
this:

spacy_singleton.py::

import spacy.en

def nlp(*args, **kwargs):
      return _spacy_instance(*args, **kwargs)

def English(*args, **kwargs):
    global _spacy_instance
    _spacy_instance = spacy.en.English(*args, **kwargs)
    return nlp

_spacy_instance = None


Yeah, global variables are bad...But sometimes they're the most practical
solution. You actually should avoid reloading the tokenizer the way you
suggest, because you would have a different string-to-integer mapping in
the two instances. The mapping would only be different for out of
vocabulary words, so it would be almost correct — the worst kind of
incorrect!

**Comment by dkleissa** [comment]
Thanks for the thorough answer and solid work.  Yes globals are terrible and should be avoided at all costs, but in this case I think you make a pretty good argument and I'm going to try out that approach. Only a sith deals in absolutes anyway :+1:

**Comment by steven-cutting** [comment]
If it helps this is what I've been doing to make it more bearable:
(This is actually similar to the above, but I use a generator instead of modifying the global inside of a function)

```
def _spacy_en():
    yield None
    spacyen = English()
    while True:
        yield spacyen

_SPACY_EN = _spacy_en()


def spacy_en():
    """
    """
    spacyen = _SPACY_EN.next()
    if spacyen:
        return spacyen
    else:
        return spacy_en()


SPACYTXTOBJ = spacy_en()("Just some plain text.")
```

**Comment by honnibal** [comment]
Inititialization time now reduced, by switching the string-table loading to use a json format.

The advice to use singletons in some situations is still relevant, but I'll close this for now.
