### ISSUE TITLE
Tokenized strings have spaces in them

### ISSUE THREAD

**Issue by viksit** [honnibal/spaCy#75]
```
n = spacy.en.English()
toks = n(u"Why am I typing all of this stuff  out?", tag=True, parse=True, entity=True)
[i.string for i in toks]
[u'Why ',
 u'am ',
 u'I ',
 u'typing ',
 u'all ',
 u'of ',
 u'this ',
 u'stuff ',
 u' ',
 u'out',
 u'?']
```

All of these words have a space afterwords. Is this intentional?

Also, 
```
[i.lemma_ for i in toks]
[u'Why',
 u'be',
 u'-PRON-',
 u'type',
 u'all',
 u'of',
 u'this',
 u'stuff',
 u' ',
 u'out',
 u'?']
```

Why does it still show PRON?

Thanks!

**Comment by honnibal** [comment]
I've been attempting to clarify this in the docs here: http://spacy.io/reference/using/token.html

token.string is whitespace padded, token.orth is not.

Internally spacy is set up so that it doesn't actually need to store the original string — it can be reconstructed exactly from the tokens. This makes it easy to calculate mark-up based on the annotations, and it makes serialization more efficient (this feature is coming soon).

**Comment by honnibal** [comment]
v0.90 addresses this by:

* Deprecate .string
* Add .text, with no whitespace padding
* Add .text_with_ws, which has the behaviour of .string
