### ISSUE TITLE
Allow strings for Python 2

### ISSUE THREAD

**Issue by ma2rten** [honnibal/spaCy#77]
I would be nice for python 2 users, who don't have to worry about internationalization, if you could also pass in a str object instead of unicode.

**Comment by fulmicoton** [comment]
How could spaCy know their encoding?

**Comment by honnibal** [comment]
Pretty much any text sample from the web will have non-ascii characters, from smart quotes, emoji, accents in names, etc. It's really much much better to enforce the encoding at the interface. Otherwise your process will fail on some text and not others.

Here are some tips to maintain sanity:

* Always use from __future__ import unicode_literals
* Always use codecs.open instead of open. Here's a snippet to do that invisibly, if you prefer:
    
    import codecs
    open = lambda loc, mode='r': codecs.open(loc, utf8, mode)

* For every input source of text, during initial development add an "assert isinstance(text, unicode)"

If you're sure your program will only ever encounter ASCII characters, try this:

    >>> class AsciiEnglish(English):
    ...     def __call__(self, string, *args, **kwargs):
    ...         return English.__call__(self, string.decode('ascii'), *args, **kwargs)
    ... 
    >>> nlp = AsciiEnglish()
    >>> nlp('I feel dirty.')
    <spacy.tokens.doc.Doc object at 0x10a4fe188>
