### ISSUE TITLE
Installation failed on Windows(cygwin)

### ISSUE THREAD

**Issue by redreamality** [honnibal/spaCy#79]
Installation failed on Windows(cygwin), 
caused by failed installation of preshed

the error infomation was KeyError: CFLAGS, which happened in the installation file setup.py of preshed, when trying to get the system config vars.

**Comment by cjmcmurtrie** [comment]
I got the same error. Python 2.7 Anaconda, Windows 8.1. Error appears after pip install spacy, but if I pip install preshed the same error appears.

**Comment by ruiEnca** [comment]
Same error here. Python 3.4 on Windows 10

**Comment by honnibal** [comment]
Unfortunately I don't have access to a Windows machine to test with at the
moment — and actually I've never tried to compile anything on Windows ever.

I'm using internals of setuptools, which seems to be the problem.
Unfortunately there's almost no API exposed in setuptools for setting
compiler options, which is why these things happen.

The naive first thing to try is just to change the call to .get, instead of
__getitem__, to work around the KeyError. You should try this on the
preshed library, instead of spaCy, as it's smaller and simpler.

More generally, is CFLAGS not the name of the compiler environment variable
for cygwin?
You can also try just commenting out these calls to rm_cflags, or wrapping
them in a try/except block?

Unfortunately it's hard to be more helpful. I don't own a Windows machine
and can't borrow one off anyone. I don't expect this to change for the next
few weeks at least.

**Comment by swayson** [comment]
I also have the same error. py2.7 Windows 7 64-bit. Tried installing with conda, but it seems there are no builds for win-64 bit.

**Comment by honnibal** [comment]
Should be passing now.
