### ISSUE TITLE
Importing gensim before spacy.en raises CompileError from murmurhash

### ISSUE THREAD

**Issue by ksindi** [honnibal/spaCy#84]
```
>>> import gensim
>>> import spacy.en
ImportError: Building module murmurhash.mrmr failed: ["CompileError: command 'gcc' failed with exit status 1\n"]
```

Importing in the reverse order is fine.
Running 64-bit Linux Mint 17.2 and Python 2.7.

**Comment by honnibal** [comment]
Nasty. Thanks for the report

I haven't had a chance to look at this but my first suspicion would be that gensim is doing some sort of monkey-patching of distutils/setuptools. Unfortunately this is sometimes necessary among C extensions because of poor support from the API.

I'll look into this and get back to you.

**Comment by honnibal** [comment]
I'm having trouble replicating this.

Was this from a clean virtualenv?

**Comment by ksindi** [comment]
Unfortunately I was using the Anaconda virtualenv with some additional installs.

**Comment by ksindi** [comment]
Not sure if this makes a difference but I was using IPython Notebook.

**Comment by honnibal** [comment]
Unfortunately Python builds can be stateful in weird ways. If you can give
me a steps to reproduce I'll take a look further. Otherwise, there's not
much I can do.

Thanks for the report though, either way — I'll keep a look out for the
problem.
